InsertStep, MoveStep Up/Down
NorbertJu/ResolutionEditor pull request #5
Opened 2019-12-18 13:45 UTC by NorbertJu

2020-01-26 14:10 UTC, crnkjck requested changes
Rezolvencia vyzera spravne, ale da sa zefektivnit. Faktorizacia nefunguje tak, ako sme sa dohodli a tiez sa da zefektivnit. Opravte, prosim.

2020-01-26 14:10 UTC, crnkjck commented on src/model/formula/Formula.Clause.js
> +  }
Lepší názov tejto metódy je `isResolvent` (je rezolventou?), pretože je to test.

Pozabudli ste asi tiež na to, že pri rezolvencii sa môžu premenovať premenné niektorej (zvyčajne prvej klauzuly) ďalšou substitúciou (ktorá ale môže substituovať iba premenné za premenné).

Signatúra tejto metódy má teda byť `isResolvent(cl1, cl2, renaming, unifier)` a začať sa má tak, že na `cl1` sa aplikuje `renaming` a potom sa na obe klauzuly aplikuje `unifier`.

Podobne nasledujúca metóda by sa mala volať `isFactor` (produktom faktorizácie sa hovorí faktory) a jej `sub` je tiez `unifier`.

2020-01-26 14:10 UTC, crnkjck commented on src/model/formula/Formula.Clause.js
> +    let newCl2 = cl2.substitute(sub);
Tieto premenne nemenite, pouzite `const` namiesto `let`.

2020-01-26 14:10 UTC, crnkjck commented on src/model/formula/Formula.Clause.js
> +        if (lit1.equals(lit2.negation())){
Tento dvojity cyklus nie je velmi efektivny. Uplne tomu nevieme zabranit, ale da sa to trocha zlepsit, ak z `lit1` vo vonkajsom cykle urobite negaciu `nli1` a tu ju porovnate s **ne**negovanym `lit2`. Teda namiesto `cl1.lits.length * cl2.lits.length` negacii sa vyrobi iba `cl1.lits.length`.

2020-01-26 14:10 UTC, crnkjck commented on src/model/formula/Formula.Clause.js
> +            .concat([newCl.lits[i]])))) {
Faktorizacia by mala fungovat tak, ze ak po unifikacii dostaneme klauzulu ` L ∨ K ∨ L ∨ M ∨ L`, faktorom je klauzula, ktorá ma o jeden vyskyt `L` menej, teda ` L ∨ K ∨ L ∨ M`. Vasa `new Clause()` bude ale obsahovat iba jeden vyskyt `L`.

Riesenie je jednoduche a navyse zase zefektivni vnorene cykly: Staci odfiltrovat `i`-ty literal  a nic dalsie do klauzuly nepridavat: `const factor = new Clause(newCl.lits.filter((_, k) => i !== k))`. Vsimnite si, ze `factor` nezavisi od `j`, takze ho mozete vyrobit uz vo *vonkajsom* cykle a hned aj porovnat s `this`. **Ak** su rovnake, vo vnutornom cykle sa pokusite najst `j`-ty literal v `newCl` rovny `i`-temu a ak existuje, vratite `true`. Inak alebo ak sa `this` nerovna `factor`, skusite dalsie `i`.

2020-02-20 09:05 UTC, merged

2020-02-21 14:33 UTC, crnkjck reviewed
Aj keď ste to už mergeli, prosím, zmeňte generátorové implementácie `getResolvents` a `getFactors`. Nerobia to, čo hovoria ich názvy, a nemajú veľmi dobrý interface.

2020-02-21 14:33 UTC, crnkjck commented on src/model/formula/Formula.Clause.js
> +  * getResolvents(cl1, cl2) {
Túto metódu ste napísali ako keby bola statická, nikde nepoužíva `this`.
Metódy je ale slušné písať tak, aby od `this` požadovali niečo, čo sa jej priamo týka.
Teda konkrétne táto metóda by sa mala používať `cl1.getResolvents(cl2)` – „`cl1`, daj mi svoje rezolventy s `cl2`“.

Navyše, substitúcie sú súčasťou rezolvenčného pravidla, mali by sa teda aplikovať v tejto metóde. Jej interface by teda mal byť: `cl1.getResolvents(cl2, renaming, unifier)` – „`cl1`, daj mi svoje rezolventy s `cl2` po aplikácii premenovania `renaming` na seba a `unifier` na obe“.

2020-02-21 14:33 UTC, crnkjck commented on src/model/formula/Formula.Clause.js
> +    for (const resolvent of this.getResolvents(newCl1, newCl2)) {
Bude korektnejšie premenovať túto metódu na `isResolventOf`.
Zmena `getResolvents` spôsobí zmenu jej volania tu.

2020-02-21 14:33 UTC, crnkjck commented on src/model/formula/Formula.Clause.js
> +  }
Podobne ako pri rezolvencii, aj tu by interface generátorovej metódy mal byť `cl.getFactors(unifier)` a mala by generovať iba **naozajstné** faktory. Súčasná implementácia generuje klauzuly, ktoré vôbec nemusia byť nie len faktormi, ale ani logickými dôsledkami vstupnej klauzuly.

Faktory môžete pomerne efektívne generovať tak, že si zoberiete `lm = this.substitute(unifier).getLitsMultiset()` a pre každú dvojicu `[lit, n]` z `lm`, kde je `n >= 2` vygenerujete kluzulu tak, že spravíte ďalší prechod cez `lm`, pri ktorom pre `[lit1, n1]` vyrobíte `n1` kópií `lit1`, ak `lit1 != lit`; ale ak `lit1 == lit`, nakopírujete ho `n - 1`-krát. Tento vnútorný prechod by sa mal dať funkcionálne napísať takto:
```javascript
lm.flatMap(([lit1, n1]) => new Array(lit1 == lit ? n1 - 1 : n1).fill(lit1))
```
Vnútorná funkcia vyrába polia s potrebným počtom kópií `lit1`, `flatMap` tieto polia pospája do jedného. Treba z toho samozrejme ešte urobiť novú klauzulu.

Zdá sa mi, že `isFactor` implementovaná pomocou takejto `getFactors` bude zhruba rovnako (ne)efektívna, ako predchádzajúca priama implementácia `isFactor`.

2020-02-21 14:33 UTC, crnkjck commented on src/model/formula/Formula.Clause.js
> +            return true;
Bude korektnejšie premenovať túto metódu na `isFactorOf`.
Po zmene `getFactors` tu ostane iba cyklus cez faktory `cl` a test `if(this.equals(factor)) return true;`.

2020-03-03 11:43 UTC, NorbertJu commented
Pripomienky zapracovane v novom pullrequeste #6